const adminPolicies = Object.freeze({
    'admin.order.refund': {
        action: 'admin.order.refund',
        resourceType: 'order',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 60,
        allowedStates: ['paid', 'processing', 'partially_fulfilled', 'delivered'],
        denyStates: ['refunded', 'chargeback', 'fraud_review'],
        requireIdempotency: true,
        highValue: true,
        riskyWrite: true,
    },
    'admin.product.delete': {
        action: 'admin.product.delete',
        resourceType: 'product',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 60,
        denyStates: ['locked', 'fraud_review'],
        riskyWrite: true,
    },
    'admin.user.role.update': {
        action: 'admin.user.role.update',
        resourceType: 'user',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 60,
        denyStates: ['deleted'],
        highValue: true,
        riskyWrite: true,
    },
    'admin.security.setting.update': {
        action: 'admin.security.setting.update',
        resourceType: 'security_setting',
        allowedRoles: ['super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 50,
        highValue: true,
        riskyWrite: true,
    },
});

module.exports = {
    adminPolicies,
};
