const adminPolicies = Object.freeze({
    'admin.order.refund': {
        action: 'admin.order.refund',
        resourceType: 'order',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 60,
        allowedStates: ['paid', 'processing', 'partially_fulfilled', 'delivered'],
        denyStates: ['refunded', 'chargeback', 'fraud_review'],
        requireIdempotency: true,
        highValue: true,
        riskyWrite: true,
    },
    'admin.product.delete': {
        action: 'admin.product.delete',
        resourceType: 'product',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 60,
        denyStates: ['locked', 'fraud_review'],
        riskyWrite: true,
    },
    'admin.user.role.update': {
        action: 'admin.user.role.update',
        resourceType: 'user',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 60,
        denyStates: ['deleted'],
        highValue: true,
        riskyWrite: true,
    },
    'admin.security.setting.update': {
        action: 'admin.security.setting.update',
        resourceType: 'security_setting',
        allowedRoles: ['super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 50,
        highValue: true,
        riskyWrite: true,
    },
    'admin.product.write': {
        action: 'admin.product.write',
        resourceType: 'product',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'MFA',
        audit: true,
        riskThreshold: 60,
        riskyWrite: true,
    },
    'admin.user.moderate': {
        action: 'admin.user.moderate',
        resourceType: 'user',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'MFA',
        audit: true,
        riskThreshold: 60,
        denyStates: ['deleted'],
        riskyWrite: true,
    },
    'admin.payment.capture': {
        action: 'admin.payment.capture',
        resourceType: 'payment',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 60,
        requireIdempotency: true,
        highValue: true,
        riskyWrite: true,
    },
    'admin.payment.refund': {
        action: 'admin.payment.refund',
        resourceType: 'payment',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 60,
        requireIdempotency: true,
        denyStates: ['chargeback', 'fraud_review'],
        highValue: true,
        riskyWrite: true,
    },
    'admin.payment.expire': {
        action: 'admin.payment.expire',
        resourceType: 'payment',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'MFA',
        audit: true,
        riskThreshold: 60,
        requireIdempotency: true,
        riskyWrite: true,
    },
    'admin.status.write': {
        action: 'admin.status.write',
        resourceType: 'status_posture',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'MFA',
        audit: true,
        riskThreshold: 60,
        riskyWrite: true,
    },
    'admin.emergency.write': {
        action: 'admin.emergency.write',
        resourceType: 'emergency_flag',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 50,
        highValue: true,
        riskyWrite: true,
    },
    'admin.ops.write': {
        action: 'admin.ops.write',
        resourceType: 'ops_control',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 50,
        highValue: true,
        riskyWrite: true,
    },
    'admin.catalog.write': {
        action: 'admin.catalog.write',
        resourceType: 'catalog',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'MFA',
        audit: true,
        riskThreshold: 60,
        requireIdempotency: true,
        riskyWrite: true,
    },
    'admin.email.write': {
        action: 'admin.email.write',
        resourceType: 'email_ops',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'MFA',
        audit: true,
        riskThreshold: 60,
        requireIdempotency: true,
        riskyWrite: true,
    },
    'admin.notification.write': {
        action: 'admin.notification.write',
        resourceType: 'notification',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'MFA',
        audit: true,
        riskThreshold: 70,
        riskyWrite: true,
    },
    'admin.fraud.write': {
        action: 'admin.fraud.write',
        resourceType: 'fraud_decision',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'MFA',
        audit: true,
        riskThreshold: 60,
        riskyWrite: true,
    },
    'admin.privileged.access': {
        action: 'admin.privileged.access',
        resourceType: 'privileged_access',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'MFA',
        audit: true,
        riskThreshold: 60,
        riskyWrite: true,
    },
    'admin.abuse.write': {
        action: 'admin.abuse.write',
        resourceType: 'abuse_denylist',
        allowedRoles: ['admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: false,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'MFA',
        audit: true,
        riskThreshold: 60,
        riskyWrite: true,
    },
});

module.exports = {
    adminPolicies,
};
