const orderPolicies = Object.freeze({
    'order.read': {
        action: 'order.read',
        resourceType: 'order',
        allowedRoles: ['buyer', 'seller', 'admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: true,
        adminBypassesOwnership: true,
        tenantRequired: false,
        sensitive: false,
        stepUp: null,
        audit: true,
        riskThreshold: 60,
        allowedStates: ['placed', 'processing', 'shipped', 'delivered', 'cancelled', 'paid', 'pending'],
        riskyWrite: false,
    },
    'order.cancel': {
        action: 'order.cancel',
        resourceType: 'order',
        allowedRoles: ['buyer', 'admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: true,
        adminBypassesOwnership: true,
        tenantRequired: false,
        sensitive: true,
        stepUp: null,
        audit: true,
        riskThreshold: 60,
        allowedStates: ['placed', 'processing', 'paid', 'pending'],
        denyStates: ['cancelled', 'refunded', 'chargeback', 'fraud_review'],
        riskyWrite: true,
    },
    'order.refund.request': {
        action: 'order.refund.request',
        resourceType: 'order',
        allowedRoles: ['buyer', 'admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: true,
        adminBypassesOwnership: true,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'MFA',
        audit: true,
        riskThreshold: 60,
        allowedStates: ['paid', 'processing', 'partially_fulfilled', 'delivered'],
        denyStates: ['refunded', 'chargeback', 'fraud_review'],
        riskyWrite: true,
    },
});

module.exports = {
    orderPolicies,
};
