const userPolicies = Object.freeze({
    'user.profile.update': {
        action: 'user.profile.update',
        resourceType: 'user',
        allowedRoles: ['buyer', 'seller', 'admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: true,
        adminBypassesOwnership: true,
        tenantRequired: false,
        sensitive: false,
        stepUp: null,
        audit: true,
        riskThreshold: 60,
        riskyWrite: true,
    },
    'user.address.update': {
        action: 'user.address.update',
        resourceType: 'address',
        allowedRoles: ['buyer', 'seller', 'admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: true,
        adminBypassesOwnership: true,
        tenantRequired: false,
        sensitive: false,
        stepUp: null,
        audit: true,
        riskThreshold: 60,
        riskyWrite: true,
    },
    'auth.mfa.disable': {
        action: 'auth.mfa.disable',
        resourceType: 'auth_factor',
        allowedRoles: ['buyer', 'seller', 'admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: true,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 50,
        highValue: true,
        riskyWrite: true,
    },
    'auth.passkey.remove': {
        action: 'auth.passkey.remove',
        resourceType: 'auth_factor',
        allowedRoles: ['buyer', 'seller', 'admin', 'super_admin'],
        requiresIdentity: true,
        requiresOwnership: true,
        tenantRequired: false,
        sensitive: true,
        stepUp: 'PASSKEY',
        audit: true,
        riskThreshold: 50,
        highValue: true,
        riskyWrite: true,
    },
});

module.exports = {
    userPolicies,
};
