services:
  aura-api:
    build:
      context: ./server
    container_name: aura-api
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/aura
      REDIS_URL: redis://redis:6379
      STATUS_MONITOR_ALLOWED_HOSTS: aura-api,localhost,127.0.0.1
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    container_name: aura-mongo
    ports:
      - "27017:27017"
    volumes:
      - aura-mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: aura-redis
    ports:
      - "6379:6379"

volumes:
  aura-mongo-data:
