const AUTH_PROVIDER_POLICY = [
    {
        key: 'password',
        label: 'Email and password',
        status: 'active',
        protocol: 'firebase_password',
        consumer: true,
        enterprise: false,
        requiredEnv: ['VITE_FIREBASE_API_KEY', 'VITE_FIREBASE_AUTH_DOMAIN'],
    },
    {
        key: 'phone',
        label: 'Firebase phone OTP',
        status: 'active',
        protocol: 'firebase_phone',
        consumer: true,
        enterprise: false,
        requiredEnv: ['VITE_MOBILE_FIREBASE_PHONE_OTP_ENABLED'],
    },
    {
        key: 'google',
        label: 'Google',
        status: 'active',
        protocol: 'oidc_via_firebase',
        consumer: true,
        enterprise: false,
        requiredEnv: ['VITE_FIREBASE_API_KEY', 'VITE_FIREBASE_AUTH_DOMAIN'],
    },
    {
        key: 'facebook',
        label: 'Facebook',
        status: 'active',
        protocol: 'oauth_via_firebase',
        consumer: true,
        enterprise: false,
        requiredEnv: ['VITE_FIREBASE_API_KEY', 'VITE_FIREBASE_AUTH_DOMAIN'],
    },
    {
        key: 'github',
        label: 'GitHub',
        status: 'active',
        protocol: 'oauth_via_firebase',
        consumer: true,
        enterprise: false,
        requiredEnv: ['VITE_FIREBASE_API_KEY', 'VITE_FIREBASE_AUTH_DOMAIN'],
    },
    {
        key: 'x',
        label: 'X',
        status: 'active',
        protocol: 'oauth_via_firebase',
        consumer: true,
        enterprise: false,
        requiredEnv: ['VITE_FIREBASE_API_KEY', 'VITE_FIREBASE_AUTH_DOMAIN'],
    },
    {
        key: 'microsoft',
        label: 'Microsoft',
        status: 'ready_when_enabled',
        protocol: 'oidc_via_firebase',
        consumer: true,
        enterprise: false,
        requiredEnv: ['VITE_FIREBASE_ENABLE_MICROSOFT_AUTH'],
    },
    {
        key: 'apple',
        label: 'Apple',
        status: 'ready_when_enabled',
        protocol: 'oidc_via_firebase',
        consumer: true,
        enterprise: false,
        requiredEnv: ['VITE_FIREBASE_ENABLE_APPLE_AUTH'],
    },
    {
        key: 'enterprise_oidc',
        label: 'Enterprise OIDC (Keycloak)',
        status: 'ready_when_configured',
        protocol: 'oidc',
        consumer: false,
        enterprise: true,
        requiredEnv: ['AUTH_PROVIDER', 'AUTH_ISSUER_URL', 'AUTH_CLIENT_ID', 'AUTH_AUDIENCE'],
    },
    {
        key: 'keycloak',
        label: 'Keycloak',
        status: 'ready_when_configured',
        protocol: 'oidc',
        consumer: false,
        enterprise: true,
        requiredEnv: [
            'AUTH_PROVIDER',
            'AUTH_ISSUER_URL',
            'AUTH_CLIENT_ID',
            'AUTH_AUDIENCE',
            'AUTH_JWKS_URL',
            'AUTH_REDIRECT_URI',
        ],
    },
    {
        key: 'enterprise_saml',
        label: 'Enterprise SAML',
        status: 'design_required',
        protocol: 'saml2',
        consumer: false,
        enterprise: true,
        requiredEnv: ['ENTERPRISE_SAML_METADATA_URL'],
    },
];

const getAuthProviderPolicy = () => AUTH_PROVIDER_POLICY.map((provider) => ({ ...provider }));

module.exports = {
    AUTH_PROVIDER_POLICY,
    getAuthProviderPolicy,
};
