const ADMIN_ROUTE_POLICIES = [
    ['GET', '/api/admin/notifications/summary', 'admin.notifications.read'],
    ['GET', '/api/admin/notifications', 'admin.notifications.read'],
    ['PATCH', '/api/admin/notifications/read-all', 'admin.notifications.write'],
    ['PATCH', '/api/admin/notifications/:notificationId/read', 'admin.notifications.write'],
    ['GET', '/api/admin/analytics/overview', 'admin.analytics.read'],
    ['GET', '/api/admin/analytics/timeseries', 'admin.analytics.read'],
    ['GET', '/api/admin/analytics/anomalies', 'admin.analytics.read'],
    ['GET', '/api/admin/analytics/export', 'admin.analytics.export'],
    ['GET', '/api/admin/analytics/bi-config', 'admin.analytics.read'],
    ['POST', '/api/admin/catalog/onboarding/validate', 'admin.catalog.write'],
    ['POST', '/api/admin/catalog/imports', 'admin.catalog.write'],
    ['GET', '/api/admin/catalog/imports/:jobId', 'admin.catalog.read'],
    ['POST', '/api/admin/catalog/imports/:jobId/publish', 'admin.catalog.write'],
    ['POST', '/api/admin/catalog/sync/run', 'admin.catalog.write'],
    ['GET', '/api/admin/catalog/health', 'admin.catalog.read'],
    ['GET', '/api/admin/catalog/search/relevance-report', 'admin.catalog.read'],
    ['GET', '/api/admin/email-ops/summary', 'admin.email.read'],
    ['GET', '/api/admin/email-ops/deliveries', 'admin.email.read'],
    ['GET', '/api/admin/email-ops/order-queue', 'admin.email.read'],
    ['GET', '/api/admin/email-ops/order-queue/:notificationId', 'admin.email.read'],
    ['POST', '/api/admin/email-ops/order-queue/:notificationId/retry', 'admin.email.write'],
    ['POST', '/api/admin/email-ops/test-send', 'admin.email.test'],
    ['GET', '/api/admin/order-emails', 'admin.email.read'],
    ['GET', '/api/admin/order-emails/:notificationId', 'admin.email.read'],
    ['POST', '/api/admin/order-emails/:notificationId/retry', 'admin.email.write'],
    ['GET', '/api/admin/users', 'admin.users.read'],
    ['GET', '/api/admin/users/:userId', 'admin.users.read'],
    ['POST', '/api/admin/users/:userId/warn', 'admin.users.moderate'],
    ['POST', '/api/admin/users/:userId/suspend', 'admin.users.moderate'],
    ['POST', '/api/admin/users/:userId/dismiss-warning', 'admin.users.moderate'],
    ['POST', '/api/admin/users/:userId/reactivate', 'admin.users.moderate'],
    ['POST', '/api/admin/users/:userId/delete', 'admin.users.delete'],
    ['GET', '/api/admin/products', 'admin.products.read'],
    ['POST', '/api/admin/products', 'admin.products.write'],
    ['GET', '/api/admin/products/:id/logs', 'admin.products.read'],
    ['GET', '/api/admin/products/:id', 'admin.products.read'],
    ['PATCH', '/api/admin/products/:id/core', 'admin.products.write'],
    ['PATCH', '/api/admin/products/:id/pricing', 'admin.products.write'],
    ['DELETE', '/api/admin/products/:id', 'admin.products.delete'],
    ['GET', '/api/admin/payments', 'admin.payments.read'],
    ['GET', '/api/admin/payments/ops/overview', 'admin.payments.read'],
    ['POST', '/api/admin/payments/ops/expire-stale', 'admin.payments.expire_stale'],
    ['GET', '/api/admin/payments/refunds/ledger', 'admin.payments.read'],
    ['PATCH', '/api/admin/payments/refunds/ledger/:orderId/:requestId/reference', 'admin.payments.refunds.write'],
    ['GET', '/api/admin/payments/:intentId', 'admin.payments.read'],
    ['POST', '/api/admin/payments/:intentId/capture', 'admin.payments.capture'],
    ['POST', '/api/admin/payments/:intentId/retry-capture', 'admin.payments.capture'],
    ['POST', '/api/admin/payments/:intentId/refunds', 'admin.payments.refunds.write'],
    ['GET', '/api/admin/ops/readiness', 'admin.ops.read'],
    ['GET', '/api/admin/ops/client-diagnostics', 'admin.ops.read'],
    ['GET', '/api/admin/ops/aws-control', 'admin.ops.read'],
    ['POST', '/api/admin/ops/smoke', 'admin.ops.smoke'],
    ['POST', '/api/admin/ops/maintenance', 'admin.ops.maintenance'],
    ['POST', '/api/admin/ops/aws-control/actions', 'admin.ops.aws_control'],
    ['GET', '/api/admin/emergency-controls', 'admin.emergency.read'],
    ['GET', '/api/admin/emergency-controls/audit', 'admin.emergency.read'],
    ['POST', '/api/admin/emergency-controls/:key/activate', 'admin.emergency.write'],
    ['POST', '/api/admin/emergency-controls/:key/deactivate', 'admin.emergency.write'],
    ['POST', '/api/admin/emergency-controls/:key/extend', 'admin.emergency.write'],
    ['PATCH', '/api/admin/emergency-controls/:key/message', 'admin.emergency.write'],
    ['GET', '/api/admin/abuse/state', 'admin.security.read'],
    ['POST', '/api/admin/abuse/denylist', 'admin.security.write'],
    ['DELETE', '/api/admin/abuse/denylist/:identity', 'admin.security.write'],
    ['GET', '/api/admin/security/assurance/:userId', 'admin.security.read'],
    ['GET', '/api/admin/status', 'admin.status.read'],
    ['POST', '/api/admin/status/components', 'admin.status.write'],
    ['PATCH', '/api/admin/status/components/:id', 'admin.status.write'],
    ['POST', '/api/admin/status/incidents', 'admin.status.write'],
    ['PATCH', '/api/admin/status/incidents/:id', 'admin.status.write'],
    ['POST', '/api/admin/status/incidents/:id/updates', 'admin.status.write'],
    ['POST', '/api/admin/status/incidents/:id/resolve', 'admin.status.write'],
    ['POST', '/api/admin/status/incidents/:id/postmortem', 'admin.status.write'],
    ['POST', '/api/admin/status/maintenance', 'admin.status.write'],
    ['GET', '/api/admin/status/subscribers', 'admin.status.read'],
    ['GET', '/api/admin/status/checks', 'admin.status.read'],
    ['POST', '/api/admin/status/monitor/run', 'admin.status.write'],
    ['POST', '/api/admin/status/seed', 'admin.status.write'],
    ['GET', '/api/admin/fraud', 'admin.fraud.read'],
    ['PATCH', '/api/admin/fraud/:decisionId/resolve', 'admin.fraud.write'],
].map(([method, path, permission]) => ({
    method,
    path,
    permission,
    role: 'admin',
    assurance: 'passkey_or_second_factor',
    middleware: ['protect', 'admin'],
}));

const SENSITIVE_USER_ROUTE_POLICIES = [
    ['GET', '/api/auth/session', 'auth.session.read', 'authenticated'],
    ['POST', '/api/auth/sync', 'auth.session.sync', 'authenticated'],
    ['POST', '/api/auth/recovery-codes', 'auth.recovery_codes.issue', 'passkey'],
    ['POST', '/api/auth/verify-device', 'auth.trusted_device.verify', 'authenticated'],
    ['PUT', '/api/users/profile', 'user.profile.write', 'authenticated'],
    ['DELETE', '/api/users/account', 'user.account.delete', 'fresh_session'],
].map(([method, path, permission, assurance]) => ({
    method,
    path,
    permission,
    role: 'user',
    assurance,
    middleware: ['protect'],
}));

const AUTHORIZATION_POLICY = [
    ...ADMIN_ROUTE_POLICIES,
    ...SENSITIVE_USER_ROUTE_POLICIES,
];

const listAuthorizationPolicy = () => AUTHORIZATION_POLICY.map((entry) => ({ ...entry }));

module.exports = {
    ADMIN_ROUTE_POLICIES,
    AUTHORIZATION_POLICY,
    SENSITIVE_USER_ROUTE_POLICIES,
    listAuthorizationPolicy,
};
