const {
    ROUTE_CLASSES,
    STATE_CHANGING_METHODS,
    getTrafficBudget,
    hasStaticExtension,
    normalizeMethod,
    normalizeRoutePath,
} = require('./trafficBudgets');

const PROFILES = Object.freeze({
    PUBLIC_BROWSING: 'A_PUBLIC_BROWSING',
    AUTH_SECURITY: 'B_AUTH_AND_ACCOUNT_SECURITY',
    PAYMENT_CHECKOUT: 'C_PAYMENT_AND_CHECKOUT',
    ADMIN_PRIVILEGED: 'D_ADMIN_AND_PRIVILEGED_ACTIONS',
    UPLOAD_MEDIA: 'E_UPLOAD_AND_MEDIA',
    AI_GATEWAY: 'F_AI_CHAT_AND_MODEL_GATEWAY',
    LIVE_SOCKET: 'G_LIVE_SOCKET_AND_VIDEO',
    WEBHOOK_INTERNAL: 'H_WEBHOOK_AND_INTERNAL',
    OBSERVABILITY: 'OBSERVABILITY_AND_HEALTH',
    STATIC_ASSETS: 'STATIC_FRONTEND_AND_ASSETS',
});

const PROFILE_LABELS = Object.freeze({
    [PROFILES.PUBLIC_BROWSING]: 'Public browsing',
    [PROFILES.AUTH_SECURITY]: 'Auth and account security',
    [PROFILES.PAYMENT_CHECKOUT]: 'Payment and checkout',
    [PROFILES.ADMIN_PRIVILEGED]: 'Admin and privileged actions',
    [PROFILES.UPLOAD_MEDIA]: 'Upload and media',
    [PROFILES.AI_GATEWAY]: 'AI/chat/model gateway',
    [PROFILES.LIVE_SOCKET]: 'Live/socket/video',
    [PROFILES.WEBHOOK_INTERNAL]: 'Webhook/internal',
    [PROFILES.OBSERVABILITY]: 'Observability/health',
    [PROFILES.STATIC_ASSETS]: 'Static frontend/assets',
});

const DEFAULT_ERROR_BEHAVIOR = 'Return a minimized JSON error with requestId, stable code, and no account or policy internals.';
const NO_AUTOMATIC_RETRY = 'No automatic retry for mutations; require user intent or idempotency-aware retry.';
const READ_RETRY = 'Read-only retry may use bounded jittered retry after cache or dependency timeout.';

const toArray = (value) => (Array.isArray(value) ? value : []);

const firstPositive = (...values) => values.find((value) => Number(value) > 0) || 0;

const limitSummary = (budget, userType) => {
    if (userType === 'admin') {
        return {
            perIp: budget.perIp,
            perUser: firstPositive(budget.perAccount, budget.perSession),
            windowSeconds: budget.windowSeconds,
        };
    }
    if (userType === 'authenticated') {
        return {
            perIp: budget.perIp,
            perUser: budget.perAccount,
            perSession: budget.perSession,
            windowSeconds: budget.windowSeconds,
        };
    }
    return {
        perIp: budget.perIp,
        perSession: budget.perSession,
        windowSeconds: budget.windowSeconds,
    };
};

const patternList = (definition) => [
    ...toArray(definition.exactPaths),
    ...toArray(definition.pathPrefixes).map((entry) => `${entry}*`),
    ...toArray(definition.pathIncludes).map((entry) => `*${entry}*`),
    ...(definition.staticAssets ? ['static-extension-assets'] : []),
];

const definePolicy = (definition) => {
    const budget = getTrafficBudget(definition.routeClass);
    const mutating = definition.methodGroup === 'mutation';
    const policy = {
        id: definition.id,
        componentName: definition.componentName,
        profile: definition.profile,
        profileLabel: PROFILE_LABELS[definition.profile] || definition.profile,
        routeClass: definition.routeClass,
        riskLevel: definition.riskLevel || budget.costRisk || 'medium',
        costClass: definition.costClass || budget.costRisk || 'medium',
        routePatterns: patternList(definition),
        exactPaths: toArray(definition.exactPaths).map(normalizeRoutePath),
        pathPrefixes: toArray(definition.pathPrefixes).map(normalizeRoutePath),
        pathIncludes: toArray(definition.pathIncludes),
        methods: toArray(definition.methods).map(normalizeMethod),
        methodGroup: definition.methodGroup || 'any',
        staticAssets: Boolean(definition.staticAssets),
        userIntent: definition.userIntent,
        abuseRisk: definition.abuseRisk,
        normalTrafficPattern: definition.normalTrafficPattern,
        burstAllowance: budget.burst,
        hardCap: budget.sustained,
        anonymousLimit: limitSummary(budget, 'anonymous'),
        authenticatedLimit: limitSummary(budget, 'authenticated'),
        adminLimit: limitSummary(budget, 'admin'),
        perIpLimit: budget.perIp,
        perUserLimit: budget.perAccount,
        perAccountLimit: budget.perAccount,
        perDeviceSessionLimit: budget.perSession,
        burstWindow: { seconds: budget.windowSeconds, max: budget.burst },
        sustainedWindow: { seconds: budget.windowSeconds, max: budget.sustained },
        bodySizeBytes: budget.maxBodyBytes,
        timeoutMs: budget.timeoutMs,
        dependencyTimeoutMs: definition.dependencyTimeoutMs || Math.max(1000, Math.floor(Number(budget.timeoutMs || 0) * 0.8)),
        retryPolicy: definition.retryPolicy || (mutating ? NO_AUTOMATIC_RETRY : READ_RETRY),
        cacheRule: definition.cacheRule || budget.cacheMode || 'no-store',
        overloadBehavior: definition.overloadBehavior || (budget.canDegrade
            ? 'May shed with 503 during overload while preserving core routes.'
            : 'Do not shed automatically; fail closed or rely on route-specific guard.'),
        publicErrorBehavior: definition.publicErrorBehavior || DEFAULT_ERROR_BEHAVIOR,
        failMode: definition.failMode || budget.productionFailMode,
        observabilityTags: Object.freeze({
            component: definition.id,
            profile: definition.profile,
            routeClass: definition.routeClass,
            metric: 'aura_traffic_budget_denied_total',
        }),
        authRequired: Boolean(definition.authRequired),
        adminRequired: Boolean(definition.adminRequired),
        signatureRequired: Boolean(definition.signatureRequired),
        flowProtectionRequired: Boolean(definition.flowProtectionRequired),
        idempotencyRequired: Boolean(definition.idempotencyRequired),
        idempotencyDecision: definition.idempotencyDecision || '',
        bodyAccepted: definition.bodyAccepted !== undefined ? Boolean(definition.bodyAccepted) : mutating,
        fileValidationRequired: Boolean(definition.fileValidationRequired),
        quotaRequired: Boolean(definition.quotaRequired),
        concurrencyCapRequired: Boolean(definition.concurrencyCapRequired),
        concurrencyCap: definition.concurrencyCap || '',
        routeLevelLimiterEvidence: definition.routeLevelLimiterEvidence || '',
        guardEvidence: definition.guardEvidence || '',
        cacheEvidence: definition.cacheEvidence || 'server/middleware/cachePolicy.js',
        timeoutEvidence: definition.timeoutEvidence || 'server/middleware/requestTimeouts.js',
        testCoverage: toArray(definition.testCoverage),
        ownerNote: definition.ownerNote || 'Runtime owner: server traffic fortress.',
    };

    return Object.freeze(policy);
};

const POLICY_DEFINITIONS = [
    {
        id: 'observability-health',
        componentName: 'Observability/health',
        profile: PROFILES.OBSERVABILITY,
        routeClass: ROUTE_CLASSES.HEALTH,
        exactPaths: ['/health', '/health/live', '/metrics'],
        pathPrefixes: ['/health/', '/api/health'],
        userIntent: 'Liveness, readiness, metrics, and low-cost status checks.',
        abuseRisk: 'Polling amplification and expensive readiness checks.',
        normalTrafficPattern: 'Frequent small GET probes from browsers, health checks, and monitors.',
        riskLevel: 'medium',
        bodyAccepted: false,
        cacheRule: 'no-store',
        overloadBehavior: 'Liveness stays cheap; readiness may fail closed with no-store 503 when dependencies are unavailable.',
        testCoverage: ['server/tests/healthRoutes.test.js', 'server/tests/backpressureReadiness.test.js'],
    },
    {
        id: 'public-status',
        componentName: 'Observability/health',
        profile: PROFILES.OBSERVABILITY,
        routeClass: ROUTE_CLASSES.STATUS_PUBLIC,
        exactPaths: ['/api/status'],
        pathPrefixes: ['/api/status/', '/api/emergency', '/status'],
        userIntent: 'Public incident, component, and maintenance status browsing.',
        abuseRisk: 'Status polling can amplify origin load during incidents.',
        normalTrafficPattern: 'Public GET reads with short cache and webhook writes from trusted monitors.',
        bodyAccepted: false,
        cacheRule: 'status-public',
        testCoverage: ['server/tests/cacheResilience.test.js'],
    },
    {
        id: 'observability-ingest',
        componentName: 'Observability/health',
        profile: PROFILES.OBSERVABILITY,
        routeClass: ROUTE_CLASSES.AUTHENTICATED_WRITE,
        pathPrefixes: ['/api/observability'],
        methodGroup: 'mutation',
        userIntent: 'Ingest bounded client diagnostics and operational telemetry.',
        abuseRisk: 'Telemetry spam, log volume amplification, and accidental sensitive payloads.',
        normalTrafficPattern: 'Small bounded POST batches from the frontend or operators.',
        authRequired: false,
        quotaRequired: true,
        retryPolicy: 'No blind retry; client diagnostics should degrade silently after a bounded attempt.',
        routeLevelLimiterEvidence: 'diagnosticsIngestLimiter and invisibleFabricProbeRateLimit',
        testCoverage: ['server/tests/observabilityRoutes.test.js'],
    },
    {
        id: 'observability-admin-read',
        componentName: 'Observability/health',
        profile: PROFILES.OBSERVABILITY,
        routeClass: ROUTE_CLASSES.ADMIN_READ,
        pathPrefixes: ['/api/observability'],
        methodGroup: 'read',
        userIntent: 'Read admin-only diagnostics and observability snapshots.',
        abuseRisk: 'Sensitive diagnostic disclosure and expensive admin reads.',
        normalTrafficPattern: 'Low-frequency admin reads.',
        authRequired: true,
        adminRequired: true,
        cacheRule: 'no-store',
        testCoverage: ['server/tests/observabilityRoutes.test.js'],
    },
    {
        id: 'static-frontend-assets',
        componentName: 'Static frontend/assets',
        profile: PROFILES.STATIC_ASSETS,
        routeClass: ROUTE_CLASSES.STATIC_PUBLIC,
        pathPrefixes: ['/assets'],
        staticAssets: true,
        userIntent: 'Load immutable frontend bundles, fonts, images, and static files.',
        abuseRisk: 'High request volume should stay at CDN/cache and avoid origin work.',
        normalTrafficPattern: 'High-volume GET/HEAD asset reads after page loads.',
        bodyAccepted: false,
        cacheRule: 'public-static',
        testCoverage: ['server/tests/cacheResilience.test.js'],
    },
    {
        id: 'provider-webhooks',
        componentName: 'Email/SMS/webhooks',
        profile: PROFILES.WEBHOOK_INTERNAL,
        routeClass: ROUTE_CLASSES.WEBHOOK,
        pathPrefixes: ['/api/payments/webhooks', '/api/email-webhooks', '/api/status/webhooks'],
        methodGroup: 'mutation',
        methods: ['POST'],
        userIntent: 'Accept signed provider callbacks and monitor webhooks.',
        abuseRisk: 'Forgery, replay, provider retry blockage, and queue amplification.',
        normalTrafficPattern: 'Small signed POST bursts from provider infrastructure.',
        signatureRequired: true,
        idempotencyRequired: true,
        retryPolicy: 'Provider retries are accepted only with signature/replay/idempotency checks.',
        overloadBehavior: 'Do not generic-shed; verify signature and replay/idempotency, then fail closed on invalid callbacks.',
        publicErrorBehavior: 'Return provider-safe generic rejection without user account details.',
        guardEvidence: 'server/controllers/paymentController.js',
        testCoverage: ['server/tests/payments.webhook.security.test.js', 'server/tests/emailWebhookRateLimitPolicy.test.js'],
    },
    {
        id: 'admin-write',
        componentName: 'Admin routes',
        profile: PROFILES.ADMIN_PRIVILEGED,
        routeClass: ROUTE_CLASSES.ADMIN_WRITE,
        pathPrefixes: ['/api/admin'],
        methodGroup: 'mutation',
        userIntent: 'Privileged configuration, user, catalog, fraud, payment, and incident mutations.',
        abuseRisk: 'Privilege escalation, destructive state change, and operational control abuse.',
        normalTrafficPattern: 'Low-volume authenticated admin actions with audit trails.',
        authRequired: true,
        adminRequired: true,
        idempotencyRequired: true,
        idempotencyDecision: 'Sensitive actions require explicit privileged guard and audit; destructive repeats must be handler-owned.',
        retryPolicy: NO_AUTOMATIC_RETRY,
        overloadBehavior: 'Fail closed; do not shed into public fallback.',
        guardEvidence: 'server/security/sensitiveActionRegistry.js',
        testCoverage: ['server/tests/adminRouteSurfaceSecurity.test.js', 'server/tests/authMiddleware.admin.test.js'],
    },
    {
        id: 'admin-read',
        componentName: 'Admin routes',
        profile: PROFILES.ADMIN_PRIVILEGED,
        routeClass: ROUTE_CLASSES.ADMIN_READ,
        pathPrefixes: ['/api/admin'],
        userIntent: 'Privileged admin dashboards, readiness, analytics, and account inspection.',
        abuseRisk: 'Sensitive data exposure and expensive data export reads.',
        normalTrafficPattern: 'Authenticated admin GET requests and low-frequency exports.',
        authRequired: true,
        adminRequired: true,
        overloadBehavior: 'May shed non-mutation reads while preserving auditability.',
        guardEvidence: 'server/middleware/authMiddleware.js',
        testCoverage: ['server/tests/adminRouteSurfaceSecurity.test.js'],
    },
    {
        id: 'password-reset',
        componentName: 'Password reset',
        profile: PROFILES.AUTH_SECURITY,
        routeClass: ROUTE_CLASSES.OTP_RESET,
        exactPaths: ['/api/otp/reset-password', '/api/auth/otp/reset-password'],
        methodGroup: 'mutation',
        methods: ['POST'],
        userIntent: 'Finalize password reset using a verified OTP flow token.',
        abuseRisk: 'Credential reset spam, account enumeration, and shared-IP lockout.',
        normalTrafficPattern: 'Very low-volume POST flow after OTP verification.',
        flowProtectionRequired: true,
        retryPolicy: 'No automatic retry; user must request a fresh flow if the token expires.',
        publicErrorBehavior: 'Generic reset failure with requestId; never reveal whether an account exists.',
        routeLevelLimiterEvidence: 'resetPasswordNetworkLimiter and resetPasswordLimiter',
        testCoverage: ['server/tests/otpRoutes.test.js', 'server/tests/trafficBudgetPolicy.test.js'],
    },
    {
        id: 'otp-send-verify',
        componentName: 'OTP send',
        profile: PROFILES.AUTH_SECURITY,
        routeClass: ROUTE_CLASSES.OTP,
        pathPrefixes: ['/api/otp', '/api/auth/otp'],
        methodGroup: 'mutation',
        methods: ['POST'],
        userIntent: 'Send, verify, or check OTP challenge state.',
        abuseRisk: 'SMS/email cost abuse, OTP brute force, and enumeration.',
        normalTrafficPattern: 'Short user-driven bursts during login or recovery.',
        flowProtectionRequired: true,
        retryPolicy: 'No automatic retry; client must honor challenge and cooldown UX.',
        publicErrorBehavior: 'Generic OTP throttling or verification failure with no account existence signal.',
        routeLevelLimiterEvidence: 'otpLimiter, verifyLimiter, checkUserLimiter',
        testCoverage: ['server/tests/otpRoutes.test.js', 'server/tests/otpSystem.test.js'],
    },
    {
        id: 'trusted-device-webauthn',
        componentName: 'MFA/passkey/Duo step-up',
        profile: PROFILES.AUTH_SECURITY,
        routeClass: ROUTE_CLASSES.AUTH_WEBAUTHN,
        exactPaths: [
            '/api/auth/verify-device',
            '/api/auth/mfa/passkey/register/options',
            '/api/auth/mfa/passkey/register/verify',
            '/api/auth/mfa/passkey/login/options',
            '/api/auth/mfa/passkey/login/verify',
            '/api/auth/mfa/passkey/remove',
        ],
        methodGroup: 'mutation',
        methods: ['POST'],
        userIntent: 'Verify trusted-device and WebAuthn-style challenge material.',
        abuseRisk: 'Challenge flooding, stale challenge replay, and account lockout.',
        normalTrafficPattern: 'A few POST attempts during step-up or trusted-device verification.',
        authRequired: true,
        flowProtectionRequired: true,
        routeLevelLimiterEvidence: 'trustedDeviceVerificationLimiter',
        testCoverage: ['server/tests/authRateLimitSecurity.test.js', 'server/tests/trafficResiliencePolicy.test.js'],
    },
    {
        id: 'mfa-passkey-duo-step-up',
        componentName: 'MFA/passkey/Duo step-up',
        profile: PROFILES.AUTH_SECURITY,
        routeClass: ROUTE_CLASSES.AUTH_LOGIN,
        pathPrefixes: ['/api/auth/mfa', '/api/auth/duo', '/api/auth/enterprise'],
        exactPaths: ['/api/auth/bootstrap-device-challenge'],
        userIntent: 'Create or verify MFA, passkey, Duo, enterprise, or trusted-device challenges.',
        abuseRisk: 'Challenge flooding, factor tampering, and account lockout.',
        normalTrafficPattern: 'Small challenge bursts during high-risk auth events.',
        authRequired: false,
        flowProtectionRequired: true,
        routeLevelLimiterEvidence: 'mfaChallengeLimiter, mfaVerifyLimiter, trustedDeviceVerificationLimiter, duoOidcLimiter',
        testCoverage: ['server/tests/mfaRolloutSmoke.test.js', 'server/tests/authRateLimitSecurity.test.js'],
    },
    {
        id: 'auth-login-session',
        componentName: 'Auth/login/session',
        profile: PROFILES.AUTH_SECURITY,
        routeClass: ROUTE_CLASSES.AUTH_LOGIN,
        pathPrefixes: ['/api/auth'],
        userIntent: 'Login, session sync, logout, recovery-code verification, and account assurance.',
        abuseRisk: 'Credential stuffing, session tampering, and enumeration.',
        normalTrafficPattern: 'Short login/session bursts, then infrequent session refresh.',
        flowProtectionRequired: true,
        publicErrorBehavior: 'Generic auth error with requestId; no email or phone enumeration.',
        routeLevelLimiterEvidence: 'authGuardRateLimit and authenticatedSessionMutationLimiter',
        testCoverage: ['server/tests/authRateLimitSecurity.test.js', 'server/tests/loginAttackSmoke.test.js'],
    },
    {
        id: 'ai-chat-model-gateway',
        componentName: 'AI assistant/chat/model gateway',
        profile: PROFILES.AI_GATEWAY,
        routeClass: ROUTE_CLASSES.AI_EXPENSIVE,
        pathPrefixes: ['/api/ai', '/api/intelligence'],
        pathIncludes: ['/visual-search'],
        userIntent: 'Invoke chat, voice, visual search, and intelligence features.',
        abuseRisk: 'Provider spend, token exhaustion, prompt abuse, and long-running streams.',
        normalTrafficPattern: 'Authenticated or risk-gated bursts with expensive dependency calls.',
        authRequired: true,
        quotaRequired: true,
        concurrencyCapRequired: true,
        concurrencyCap: 'Provider quota and chatQuotaService control expensive model pressure.',
        retryPolicy: 'No blind retry for model calls; return graceful failure or stream termination.',
        routeLevelLimiterEvidence: 'aiChatLimiter, aiVoiceLimiter, aiSessionLimiter',
        testCoverage: ['server/tests/aiRateLimitPolicy.test.js', 'server/tests/providerCircuitBreakerReadiness.test.js'],
    },
    {
        id: 'payment-checkout',
        componentName: 'Payment/checkout/order',
        profile: PROFILES.PAYMENT_CHECKOUT,
        routeClass: ROUTE_CLASSES.PAYMENT,
        pathPrefixes: ['/api/payments', '/api/checkout'],
        userIntent: 'Create, confirm, capture, refund, or inspect payment/checkout state.',
        abuseRisk: 'Double mutation, refund abuse, provider cost, and payment ownership bypass.',
        normalTrafficPattern: 'Low-volume authenticated mutations and reads during checkout.',
        authRequired: true,
        idempotencyRequired: true,
        idempotencyDecision: 'Payment intent, provider idempotency, and state-machine guards own duplicate prevention.',
        retryPolicy: NO_AUTOMATIC_RETRY,
        routeLevelLimiterEvidence: 'paymentIntentRateLimit and paymentIntentLimiter',
        guardEvidence: 'server/services/payments/paymentService.js',
        testCoverage: ['server/tests/paymentSecurityGuards.test.js', 'server/tests/paymentOrderIntegrity.test.js'],
    },
    {
        id: 'cart-order-mutations',
        componentName: 'Cart',
        profile: PROFILES.PAYMENT_CHECKOUT,
        routeClass: ROUTE_CLASSES.AUTHENTICATED_WRITE,
        pathPrefixes: ['/api/cart', '/api/orders', '/api/trade-in', '/api/price-alerts'],
        methodGroup: 'mutation',
        userIntent: 'Mutate cart, order, trade-in, and price-alert state.',
        abuseRisk: 'State replay, ownership bypass, and write amplification.',
        normalTrafficPattern: 'Authenticated user-driven cart/order mutations.',
        authRequired: true,
        idempotencyRequired: true,
        idempotencyDecision: 'Canonical cart commands and order state machines must reject unsafe repeats.',
        retryPolicy: NO_AUTOMATIC_RETRY,
        guardEvidence: 'server/services/orderPlacementService.js',
        testCoverage: ['server/tests/orderControllerCreate.test.js', 'server/tests/orderPlacementService.test.js'],
    },
    {
        id: 'cart-order-reads',
        componentName: 'Cart',
        profile: PROFILES.PAYMENT_CHECKOUT,
        routeClass: ROUTE_CLASSES.AUTHENTICATED_READ,
        pathPrefixes: ['/api/cart', '/api/orders', '/api/trade-in', '/api/price-alerts'],
        methodGroup: 'read',
        userIntent: 'Read cart, order, trade-in, and price-alert state.',
        abuseRisk: 'Ownership bypass and repeated account data reads.',
        normalTrafficPattern: 'Authenticated GET reads during shopping and account review.',
        authRequired: true,
        cacheRule: 'no-store',
        testCoverage: ['server/tests/profileSecurity.test.js', 'server/tests/paymentOrderIntegrity.test.js'],
    },
    {
        id: 'live-socket-video',
        componentName: 'LiveKit/socket/video support',
        profile: PROFILES.LIVE_SOCKET,
        routeClass: ROUTE_CLASSES.AUTHENTICATED_WRITE,
        pathIncludes: ['/video/', '/live-call', '/socket'],
        methodGroup: 'mutation',
        userIntent: 'Mint or update server-side live/video session state.',
        abuseRisk: 'Room flooding, token mint abuse, and cross-listing session hijack.',
        normalTrafficPattern: 'Short authenticated bursts around video call start/join/end.',
        authRequired: true,
        idempotencyRequired: true,
        concurrencyCapRequired: true,
        concurrencyCap: 'Socket service and listing live-call limiter cap token minting.',
        routeLevelLimiterEvidence: 'listingLiveCallTokenLimiter',
        guardEvidence: 'server/tests/liveCallSessionKeyAuthz.test.js',
        testCoverage: ['server/tests/liveCallSessionKeyAuthz.test.js'],
    },
    {
        id: 'upload-review-media',
        componentName: 'Upload/review media',
        profile: PROFILES.UPLOAD_MEDIA,
        routeClass: ROUTE_CLASSES.UPLOAD,
        pathPrefixes: ['/api/uploads', '/uploads'],
        methodGroup: 'mutation',
        userIntent: 'Sign, upload, scan, quarantine, or read review media assets.',
        abuseRisk: 'Storage, CPU, malware scanning, and unbounded file payload abuse.',
        normalTrafficPattern: 'Small authenticated upload bursts and public media reads.',
        authRequired: true,
        fileValidationRequired: true,
        retryPolicy: 'No automatic upload retry; user-initiated retry after validation failure.',
        routeLevelLimiterEvidence: 'uploadAssetLimiter and traffic upload budget',
        guardEvidence: 'server/services/malwareScanService.js',
        testCoverage: ['server/tests/productReviewMediaSecurity.test.js', 'server/tests/uploadSecurityPipeline.test.js'],
    },
    {
        id: 'recommendation-events',
        componentName: 'Recommendation events',
        profile: PROFILES.PUBLIC_BROWSING,
        routeClass: ROUTE_CLASSES.AUTHENTICATED_WRITE,
        pathPrefixes: ['/api/recommendation-events'],
        methodGroup: 'mutation',
        userIntent: 'Record bounded recommendation interaction events.',
        abuseRisk: 'Analytics write amplification and event spam.',
        normalTrafficPattern: 'Small optional-auth event writes during browsing.',
        authRequired: false,
        quotaRequired: true,
        retryPolicy: 'No blind retry; event loss is preferable to write amplification.',
        guardEvidence: 'server/routes/recommendationEventRoutes.js',
        testCoverage: ['server/tests/rateLimitCoverage.test.js'],
    },
    {
        id: 'marketplace-mutations',
        componentName: 'Search/listing/marketplace',
        profile: PROFILES.PUBLIC_BROWSING,
        routeClass: ROUTE_CLASSES.AUTHENTICATED_WRITE,
        pathPrefixes: ['/api/products', '/api/listings', '/api/recommendations'],
        methodGroup: 'mutation',
        userIntent: 'Create marketplace listings, messages, recommendations, or product-side state.',
        abuseRisk: 'Marketplace spam, write amplification, and ownership bypass.',
        normalTrafficPattern: 'Authenticated seller/user mutations mixed with optional recommendation events.',
        authRequired: true,
        retryPolicy: NO_AUTOMATIC_RETRY,
        routeLevelLimiterEvidence: 'listingMutationRateLimit and listingMutationLimiter',
        testCoverage: ['server/tests/marketplaceIntegrityService.test.js', 'server/tests/rateLimitCoverage.test.js'],
    },
    {
        id: 'product-search-browsing',
        componentName: 'Search/listing/marketplace',
        profile: PROFILES.PUBLIC_BROWSING,
        routeClass: ROUTE_CLASSES.PUBLIC_SEARCH,
        pathPrefixes: ['/api/products', '/api/listings', '/api/recommendations'],
        userIntent: 'Browse products, listings, marketplace search, and recommendations.',
        abuseRisk: 'Scraping, cache bypass, query fanout, and database pressure.',
        normalTrafficPattern: 'Bursty public GET reads with query and page-size budgets.',
        cacheRule: 'public-short',
        testCoverage: ['server/tests/databasePressureResilience.test.js', 'server/tests/cacheResilience.test.js'],
    },
    {
        id: 'i18n-translation',
        componentName: 'i18n/translation',
        profile: PROFILES.PUBLIC_BROWSING,
        routeClass: ROUTE_CLASSES.AUTHENTICATED_WRITE,
        pathPrefixes: ['/api/i18n'],
        methodGroup: 'mutation',
        userIntent: 'Request runtime translation or locale-support operations.',
        abuseRisk: 'Provider cost, repeated translation work, and cache bypass.',
        normalTrafficPattern: 'Small locale bursts from UI text surfaces.',
        quotaRequired: true,
        retryPolicy: 'Bounded retry only when cached translation fallback is unavailable.',
        routeLevelLimiterEvidence: 'i18n route distributed limiter',
        testCoverage: ['server/tests/i18nRateLimitPolicy.test.js'],
    },
    {
        id: 'public-api-read',
        componentName: 'Product browsing',
        profile: PROFILES.PUBLIC_BROWSING,
        routeClass: ROUTE_CLASSES.PUBLIC_READ,
        pathPrefixes: ['/api/users', '/api/security', '/api/markets', '/api/support', '/api/notifications'],
        methodGroup: 'read',
        userIntent: 'Low-cost public or optionally-authenticated API reads.',
        abuseRisk: 'Repeated reads, cache bypass, and accidental sensitive caching.',
        normalTrafficPattern: 'Normal UI GET reads that must remain smooth.',
        cacheRule: 'public-short',
        testCoverage: ['server/tests/cacheResilience.test.js'],
    },
    {
        id: 'user-support-mutations',
        componentName: 'Auth/login/session',
        profile: PROFILES.AUTH_SECURITY,
        routeClass: ROUTE_CLASSES.AUTHENTICATED_WRITE,
        pathPrefixes: ['/api/users', '/api/security', '/api/support', '/api/notifications'],
        methodGroup: 'mutation',
        userIntent: 'Mutate user profile, account, support, security, and notification state.',
        abuseRisk: 'Account state tampering, support spam, and notification write amplification.',
        normalTrafficPattern: 'Authenticated user-driven POST/PUT/PATCH/DELETE operations.',
        authRequired: true,
        retryPolicy: NO_AUTOMATIC_RETRY,
        guardEvidence: 'server/middleware/authMiddleware.js',
        testCoverage: ['server/tests/profileSecurity.test.js', 'server/tests/supportRoutes.security.test.js'],
    },
    {
        id: 'internal-jobs-workers',
        componentName: 'Internal jobs/workers',
        profile: PROFILES.WEBHOOK_INTERNAL,
        routeClass: ROUTE_CLASSES.AUTHENTICATED_WRITE,
        pathPrefixes: ['/api/internal'],
        userIntent: 'Run authenticated internal cron, worker, and service operations.',
        abuseRisk: 'Worker amplification, unauthorized job execution, and costly internal AI calls.',
        normalTrafficPattern: 'Low-frequency signed internal service calls.',
        authRequired: true,
        signatureRequired: true,
        idempotencyRequired: true,
        retryPolicy: 'Worker retry must be bounded, authenticated, and idempotency-aware.',
        guardEvidence: 'server/routes/internalOpsRoutes.js',
        testCoverage: ['server/tests/backpressureReadiness.test.js'],
    },
    {
        id: 'api-mutation-fallback',
        componentName: 'Product browsing',
        profile: PROFILES.PUBLIC_BROWSING,
        routeClass: ROUTE_CLASSES.AUTHENTICATED_WRITE,
        pathPrefixes: ['/api'],
        methodGroup: 'mutation',
        userIntent: 'Fallback for new API mutations until a component-specific policy is added.',
        abuseRisk: 'New mutation route without explicit policy.',
        normalTrafficPattern: 'Should be temporary; regression audit requires explicit coverage for top-level mounts.',
        authRequired: true,
        retryPolicy: NO_AUTOMATIC_RETRY,
        ownerNote: 'Fallback only; add a component policy for new route families.',
        testCoverage: ['server/tests/trafficPolicyRegistry.test.js'],
    },
    {
        id: 'api-read-fallback',
        componentName: 'Product browsing',
        profile: PROFILES.PUBLIC_BROWSING,
        routeClass: ROUTE_CLASSES.PUBLIC_READ,
        pathPrefixes: ['/api'],
        userIntent: 'Fallback for low-cost public API reads until a component-specific policy is added.',
        abuseRisk: 'New route may be under-classified if left on fallback.',
        normalTrafficPattern: 'Low-cost GET reads.',
        cacheRule: 'public-short',
        ownerNote: 'Fallback only; add a component policy for new route families.',
        testCoverage: ['server/tests/trafficPolicyRegistry.test.js'],
    },
    {
        id: 'static-fallback',
        componentName: 'Static frontend/assets',
        profile: PROFILES.STATIC_ASSETS,
        routeClass: ROUTE_CLASSES.STATIC_PUBLIC,
        pathPrefixes: ['/'],
        userIntent: 'Serve frontend shell or safe static fallback.',
        abuseRisk: 'Origin hit amplification if CDN/cache is bypassed.',
        normalTrafficPattern: 'GET/HEAD frontend shell and static fallback reads.',
        bodyAccepted: false,
        cacheRule: 'public-static',
        testCoverage: ['server/tests/cacheResilience.test.js'],
    },
];

const TRAFFIC_POLICY_REGISTRY = Object.freeze(POLICY_DEFINITIONS.map(definePolicy));

const methodMatches = (policy, method) => {
    const normalizedMethod = normalizeMethod(method);
    if (policy.methods.length) return policy.methods.includes(normalizedMethod);
    if (policy.methodGroup === 'mutation') return STATE_CHANGING_METHODS.has(normalizedMethod);
    if (policy.methodGroup === 'read') return !STATE_CHANGING_METHODS.has(normalizedMethod);
    return true;
};

const pathMatches = (policy, routePath) => {
    if (policy.staticAssets && hasStaticExtension(routePath)) return true;
    if (policy.exactPaths.includes(routePath)) return true;
    if (policy.pathPrefixes.some((prefix) => routePath === prefix || routePath.startsWith(`${prefix}/`) || routePath.startsWith(prefix))) return true;
    return policy.pathIncludes.some((needle) => routePath.includes(needle));
};

const getTrafficPolicyForRoute = ({ method = 'GET', path = '/', originalUrl = '' } = {}) => {
    const routePath = normalizeRoutePath(path || originalUrl);
    return TRAFFIC_POLICY_REGISTRY.find((policy) => methodMatches(policy, method) && pathMatches(policy, routePath))
        || TRAFFIC_POLICY_REGISTRY[TRAFFIC_POLICY_REGISTRY.length - 1];
};

const classifyRouteFromRegistry = (route = {}) => getTrafficPolicyForRoute(route).routeClass;

const getTrafficPolicyById = (id) => TRAFFIC_POLICY_REGISTRY.find((policy) => policy.id === id) || null;

const listTrafficPolicies = () => TRAFFIC_POLICY_REGISTRY.slice();

const listTrafficComponents = () => Array.from(new Set(TRAFFIC_POLICY_REGISTRY.map((policy) => policy.componentName)));

const buildTrafficPolicyMatrix = () => TRAFFIC_POLICY_REGISTRY.map((policy) => ({
    component: policy.componentName,
    profile: policy.profileLabel,
    routeExamples: policy.routePatterns.join(', '),
    userType: policy.adminRequired ? 'admin' : (policy.authRequired ? 'authenticated' : 'anonymous or mixed'),
    abuseRisk: policy.abuseRisk,
    rateLimit: `ip ${policy.perIpLimit}/${policy.sustainedWindow.seconds}s; user ${policy.perUserLimit || 0}/${policy.sustainedWindow.seconds}s; session ${policy.perDeviceSessionLimit || 0}/${policy.sustainedWindow.seconds}s`,
    burstLimit: `${policy.burstWindow.max}/${policy.burstWindow.seconds}s`,
    sustainedLimit: `${policy.sustainedWindow.max}/${policy.sustainedWindow.seconds}s`,
    bodySizeBudget: policy.bodySizeBytes,
    timeoutBudget: policy.timeoutMs,
    retryPolicy: policy.retryPolicy,
    cachePolicy: policy.cacheRule,
    overloadResponse: policy.overloadBehavior,
    failMode: policy.failMode,
    tests: policy.testCoverage.join(', '),
    ownerNote: policy.ownerNote,
}));

module.exports = {
    PROFILES,
    PROFILE_LABELS,
    TRAFFIC_POLICY_REGISTRY,
    buildTrafficPolicyMatrix,
    classifyRouteFromRegistry,
    getTrafficPolicyById,
    getTrafficPolicyForRoute,
    listTrafficComponents,
    listTrafficPolicies,
};
