#!/usr/bin/env bash
# Production Mongo logical backup. Runs ON the backend EC2 host via SSM
# (dispatched by .github/workflows/production-db-backup.yml) - mongodump is a
# host-level tool and the database is not part of the api compose stack.
# Hot logical per-collection dump uploaded to S3 with checksums and a
# manifest. No --oplog: the database is an Atlas shared-tier cluster, which
# does not expose the oplog (mongodump --oplog exits 1 with no error output
# there). Restore with `mongorestore --archive --gzip`.
set -euo pipefail

BACKUP_ID="$(date -u +%Y%m%d-%H%M%S)"
WORK_DIR="/opt/aura/backup-work/${BACKUP_ID}"
mkdir -p "$WORK_DIR"
trap 'rm -rf "$WORK_DIR"' EXIT

MONGO_URI=""
for env_file in /opt/aura/shared/runtime-secrets.env /opt/aura/shared/base.env; do
  if [ -z "$MONGO_URI" ] && grep -q '^MONGO_URI=' "$env_file" 2>/dev/null; then
    MONGO_URI="$(grep '^MONGO_URI=' "$env_file" | head -1 | cut -d= -f2-)"
  fi
done
[ -n "$MONGO_URI" ] || { echo "MONGO_URI not found in /opt/aura/shared/*.env"; exit 1; }
[ -n "${AURA_BACKUP_BUCKET:-}" ] || { echo "AURA_BACKUP_BUCKET is required"; exit 1; }
[ -n "${AWS_REGION:-}" ] || { echo "AWS_REGION is required"; exit 1; }

if ! command -v mongodump >/dev/null 2>&1; then
  arch="$(uname -m)"
  case "$arch" in
    x86_64) tools_arch="x86_64" ;;
    aarch64) tools_arch="aarch64" ;;
    *) echo "Unsupported architecture: $arch"; exit 1 ;;
  esac
  tools_rpm="/tmp/mongodb-database-tools.rpm"
  curl -fsSL "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-amazon2023-${tools_arch}-100.11.0.rpm" -o "$tools_rpm"
  sudo dnf install -y "$tools_rpm" >/dev/null
fi

mongodump --uri "$MONGO_URI" --archive --gzip --quiet > "$WORK_DIR/mongo.archive.gz"
test -s "$WORK_DIR/mongo.archive.gz"

# Client-side envelope encryption: the archive is encrypted BEFORE upload with a
# data key generated by KMS (AURA_BACKUP_ENCRYPTION_KMS_KEY_ID), so the S3 object
# is useless without the KMS key even if bucket credentials are compromised.
# AURA_BACKUP_ENCRYPTION_MASTER_KEY (dev/test only) bypasses KMS. Unset vars =
# legacy unencrypted upload.
ARCHIVE_FILE="mongo.archive.gz"
ENCRYPTION_MODE="none"
if [ -n "${AURA_BACKUP_ENCRYPTION_KMS_KEY_ID:-}" ] || [ -n "${AURA_BACKUP_ENCRYPTION_MASTER_KEY:-}" ]; then
  [ -n "${BACKUP_CRYPTO_JS:-}" ] && [ -f "${BACKUP_CRYPTO_JS}" ] || { echo "BACKUP_CRYPTO_JS must point to backup-archive-crypto.js for encrypted backups"; exit 1; }

  run_backup_crypto() {
    local mode="$1" in_file="$2" out_file="$3"
    if command -v node >/dev/null 2>&1; then
      node "$BACKUP_CRYPTO_JS" "$mode" "$in_file" "$out_file"
    elif command -v docker >/dev/null 2>&1; then
      # The host has no node.js: run the zero-dependency crypto in a throwaway
      # node container. --network none (KMS was already contacted on the host)
      # so the in-memory data key cannot leave the box.
      docker run --rm --network none \
        -v "$(cd "$(dirname "$BACKUP_CRYPTO_JS")" && pwd):/crypto:ro" \
        -v "$WORK_DIR:/work" \
        -e DEK_B64 -e WRAPPED_B64 -e AURA_BACKUP_ENCRYPTION_MASTER_KEY \
        node:22-alpine node "/crypto/$(basename "$BACKUP_CRYPTO_JS")" \
        "$mode" "/work/$(basename "$in_file")" "/work/$(basename "$out_file")"
    else
      echo "Encrypted backups require node or docker on the host"; exit 1
    fi
  }

  if [ -n "${AURA_BACKUP_ENCRYPTION_KMS_KEY_ID:-}" ]; then
    aws kms generate-data-key --key-id "$AURA_BACKUP_ENCRYPTION_KMS_KEY_ID" --key-spec AES_256 \
      --region "$AWS_REGION" --output json > "$WORK_DIR/datakey.json"
    export DEK_B64="$(jq -r '.Plaintext' "$WORK_DIR/datakey.json")"
    export WRAPPED_B64="$(jq -r '.CiphertextBlob' "$WORK_DIR/datakey.json")"
    rm -f "$WORK_DIR/datakey.json"
    ENCRYPTION_MODE="kms-envelope"
  else
    export AURA_BACKUP_ENCRYPTION_MASTER_KEY
    ENCRYPTION_MODE="local-master"
  fi

  run_backup_crypto encrypt "$WORK_DIR/mongo.archive.gz" "$WORK_DIR/mongo.archive.gz.enc"
  test -s "$WORK_DIR/mongo.archive.gz.enc" || { echo "Encrypted archive is missing"; exit 1; }
  rm -f "$WORK_DIR/mongo.archive.gz"
  unset DEK_B64 WRAPPED_B64 AURA_BACKUP_ENCRYPTION_MASTER_KEY || true
  ARCHIVE_FILE="mongo.archive.gz.enc"
fi

(cd "$WORK_DIR" && sha256sum "$ARCHIVE_FILE" > checksums.sha256)
printf '{"formatVersion":2,"createdAt":"%s","environment":"production","consistencyMode":"hot-logical-per-collection","encryption":"%s","restoreRequires":"mongorestore --archive --gzip","upload":"ec2-direct-s3"}\n' \
  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$ENCRYPTION_MODE" > "$WORK_DIR/manifest.json"

# --sse AES256: S3-managed encryption (SSE-S3) as defense in depth under the
# client-side envelope, so archives are never at rest unencrypted even if
# bucket default encryption is misconfigured.
aws s3 cp "$WORK_DIR/$ARCHIVE_FILE" "s3://${AURA_BACKUP_BUCKET}/production/mongo/${BACKUP_ID}/$ARCHIVE_FILE" \
  --region "$AWS_REGION" --sse AES256 --metadata "environment=production,backup-id=${BACKUP_ID},encryption=${ENCRYPTION_MODE}" --only-show-errors
aws s3 cp "$WORK_DIR/checksums.sha256" "s3://${AURA_BACKUP_BUCKET}/production/mongo/${BACKUP_ID}/checksums.sha256" --sse AES256 --only-show-errors
aws s3 cp "$WORK_DIR/manifest.json" "s3://${AURA_BACKUP_BUCKET}/production/mongo/${BACKUP_ID}/manifest.json" --sse AES256 --only-show-errors

echo "BACKUP_S3_KEY=production/mongo/${BACKUP_ID}/$ARCHIVE_FILE"
echo "BACKUP_ENCRYPTION=$ENCRYPTION_MODE"
