{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secrets" (include "aura-api.fullname" .)) .Values.secrets.existingSecret }}
  labels:
    {{- include "aura-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
