const crypto = require('crypto');
const logger = require('../utils/logger');

// Envelope encryption for sensitive fields at rest.
//
// Key hierarchy: a data-encryption key (DEK) is generated by AWS KMS
// (GenerateDataKey) and lives ONLY in process memory; KMS holds the wrapping
// key (KEK). Every record is encrypted with the cached DEK under a fresh
// 12-byte IV (AES-256-GCM), so a leaked MongoDB dump without the KMS key
// reveals nothing. KMS is contacted once per process (plus re-primes), not
// per record.
//
// Ciphertext format (base64url segments): v1.<keyVersion>.<iv>.<tag>.<ct>
// keyVersion enables zero-downtime rotation: set a new DEK version as current
// and move the old one to FIELD_ENCRYPTION_PREVIOUS_KEYS for decryption.
//
// Rollout: FIELD_ENCRYPTION_ENABLED=false (default) makes encrypt()/decrypt()
// pass-through no-ops, so existing plaintext keeps working and the flag is the
// kill switch. Enabling requires key material: KMS in production; a local
// FIELD_ENCRYPTION_MASTER_KEY is only allowed outside production.

const FORMAT_VERSION = 'v1';
const IV_BYTES = 12;
const TAG_BYTES = 16;
const DEK_BYTES = 32;

const parseBoolean = (value, fallback = false) => {
    if (value === undefined || value === null || value === '') return fallback;
    const normalized = String(value).trim().toLowerCase();
    return ['1', 'true', 'yes', 'on'].includes(normalized);
};

const isProduction = () => process.env.NODE_ENV === 'production';

let kmsDataKey = null; // { keyVersion, key (Buffer) }
let previousKeys = new Map(); // keyVersion -> Buffer
let primingPromise = null;

const isFieldEncryptionEnabled = () => parseBoolean(process.env.FIELD_ENCRYPTION_ENABLED, false);

const resolveKmsKeyId = () => String(process.env.FIELD_ENCRYPTION_KMS_KEY_ID || '').trim();

const resolveLocalMasterKey = () => String(process.env.FIELD_ENCRYPTION_MASTER_KEY || '').trim();

const buildPreviousKeys = () => {
    const map = new Map();
    String(process.env.FIELD_ENCRYPTION_PREVIOUS_KEYS || '')
        .split(',')
        .map((entry) => entry.trim())
        .filter(Boolean)
        .forEach((entry) => {
            const separator = entry.indexOf(':');
            if (separator <= 0) return;
            const [version, material] = [entry.slice(0, separator).trim(), entry.slice(separator + 1).trim()];
            if (version && material) map.set(version, normalizeKeyMaterial(material));
        });
    return map;
};

const normalizeKeyMaterial = (material) => {
    const raw = Buffer.from(String(material || ''), 'utf8');
    // Accept raw 32 bytes, base64/hex encoded 32 bytes, or derive via scrypt.
    if (raw.length === DEK_BYTES) return raw;
    try {
        const decoded = Buffer.from(String(material || ''), 'base64');
        if (decoded.length === DEK_BYTES) return decoded;
    } catch {
        // fall through to KDF
    }
    return crypto.scryptSync(String(material || ''), 'aura-field-encryption-kdf', DEK_BYTES);
};

const assertEnablementContract = () => {
    if (!isFieldEncryptionEnabled()) return;
    if (resolveKmsKeyId()) return;
    if (resolveLocalMasterKey()) {
        if (isProduction()) {
            throw new Error('FIELD_ENCRYPTION_MASTER_KEY is not allowed in production; configure FIELD_ENCRYPTION_KMS_KEY_ID');
        }
        return;
    }
    throw new Error('FIELD_ENCRYPTION_ENABLED requires FIELD_ENCRYPTION_KMS_KEY_ID (or FIELD_ENCRYPTION_MASTER_KEY outside production)');
};

const loadKmsDataKey = async () => {
    const keyId = resolveKmsKeyId();
    const { KMSClient, GenerateDataKeyCommand } = require('@aws-sdk/client-kms');
    const client = new KMSClient({});
    const response = await client.send(new GenerateDataKeyCommand({ KeyId: keyId, KeySpec: 'AES_256' }));
    if (!response?.Plaintext || response.Plaintext.length !== DEK_BYTES) {
        throw new Error('KMS GenerateDataKey returned unexpected key material');
    }
    return Buffer.from(response.Plaintext);
};

const loadLocalDataKey = () => normalizeKeyMaterial(resolveLocalMasterKey());

const nextKeyVersion = () => `k${Date.now().toString(36)}${crypto.randomBytes(2).toString('hex')}`;

// Prime the in-memory DEK. Idempotent and safe to call at every startup.
const primeFieldEncryption = async () => {
    assertEnablementContract();
    if (!isFieldEncryptionEnabled()) return { enabled: false };
    if (kmsDataKey) return { enabled: true, cached: true, keyVersion: kmsDataKey.keyVersion };
    if (primingPromise) return primingPromise;

    primingPromise = (async () => {
        previousKeys = buildPreviousKeys();
        let key;
        let keyVersion = String(process.env.FIELD_ENCRYPTION_KEY_VERSION || '').trim();
        if (resolveKmsKeyId()) {
            key = await loadKmsDataKey();
            if (!keyVersion) keyVersion = nextKeyVersion();
        } else {
            key = loadLocalDataKey();
            if (!keyVersion) keyVersion = 'local';
            if (keyVersion === 'local' && previousKeys.has('local')) previousKeys.delete('local');
        }
        kmsDataKey = { keyVersion, key };
        logger.info('field_encryption.primed', { keyVersion, provider: resolveKmsKeyId() ? 'kms' : 'local' });
        return { enabled: true, keyVersion };
    })();

    try {
        return await primingPromise;
    } finally {
        primingPromise = null;
    }
};

const requireKeyMaterial = () => {
    if (!kmsDataKey) {
        throw new Error('Field encryption key material is not primed; call primeFieldEncryption() before encrypted reads/writes');
    }
    return kmsDataKey;
};

const b64url = (buffer) => Buffer.from(buffer).toString('base64url');

const encrypt = (plaintext) => {
    if (plaintext === undefined || plaintext === null || plaintext === '') return plaintext;
    if (typeof plaintext !== 'string') plaintext = String(plaintext);
    if (!isFieldEncryptionEnabled()) return plaintext;

    const { key, keyVersion } = requireKeyMaterial();
    const iv = crypto.randomBytes(IV_BYTES);
    const cipher = crypto.createCipheriv('aes-256-gcm', key, iv, { authTagLength: TAG_BYTES });
    let encrypted = cipher.update(plaintext, 'utf8');
    encrypted = Buffer.concat([encrypted, cipher.final()]);
    return [
        FORMAT_VERSION,
        b64url(keyVersion),
        b64url(iv),
        b64url(cipher.getAuthTag()),
        b64url(encrypted),
    ].join('.');
};

const decrypt = (ciphertext) => {
    if (ciphertext === undefined || ciphertext === null || ciphertext === '') return ciphertext;
    if (typeof ciphertext !== 'string') return ciphertext;
    if (!ciphertext.startsWith(`${FORMAT_VERSION}.`)) return ciphertext; // legacy plaintext (dual-read)

    const [version, keyVersionRaw, ivRaw, tagRaw, ctRaw] = ciphertext.split('.');
    if (version !== FORMAT_VERSION || !keyVersionRaw || !ivRaw || !tagRaw || !ctRaw) return null;

    const keyVersion = Buffer.from(keyVersionRaw, 'base64url').toString('utf8');
    let key = null;
    if (kmsDataKey && kmsDataKey.keyVersion === keyVersion) {
        key = kmsDataKey.key;
    } else if (previousKeys.has(keyVersion)) {
        key = previousKeys.get(keyVersion);
    } else if (kmsDataKey) {
        key = kmsDataKey.key; // tolerate mismatched versions after untracked rotation
    }
    if (!key) return null;

    try {
        const decipher = crypto.createDecipheriv('aes-256-gcm', key, Buffer.from(ivRaw, 'base64url'), {
            authTagLength: TAG_BYTES,
        });
        decipher.setAuthTag(Buffer.from(tagRaw, 'base64url'));
        const decrypted = Buffer.concat([decipher.update(Buffer.from(ctRaw, 'base64url')), decipher.final()]);
        return decrypted.toString('utf8');
    } catch {
        return null;
    }
};

const isEncrypted = (value) => typeof value === 'string' && value.startsWith(`${FORMAT_VERSION}.`);

const isPrimed = () => Boolean(kmsDataKey);

const assertFieldEncryptionConfig = () => assertEnablementContract();

module.exports = {
    primeFieldEncryption,
    encrypt,
    decrypt,
    isEncrypted,
    isFieldEncryptionEnabled,
    isPrimed,
    assertFieldEncryptionConfig,
};
