const crypto = require('crypto');
const { deriveAes256GcmKey } = require('../utils/cryptoKdf');
const logger = require('../utils/logger');

// Envelope encryption for sensitive fields at rest.
//
// Key hierarchy: a data-encryption key (DEK) is generated by AWS KMS
// (GenerateDataKey) and lives ONLY in process memory; KMS holds the wrapping
// key (KEK). Every record is encrypted with the cached DEK under a fresh
// 12-byte IV (AES-256-GCM), so a leaked MongoDB dump without the KMS key
// reveals nothing. KMS is contacted once per process (plus re-primes), not
// per record.
//
// Ciphertext format (base64url segments): v1.<keyVersion>.<iv>.<tag>.<ct>
// keyVersion enables zero-downtime rotation: set a new DEK version as current
// and move the old one to FIELD_ENCRYPTION_PREVIOUS_KEYS for decryption.
//
// Rollout: FIELD_ENCRYPTION_ENABLED=false (default) makes encrypt()/decrypt()
// pass-through no-ops, so existing plaintext keeps working and the flag is the
// kill switch. Enabling requires key material: KMS in production; a local
// FIELD_ENCRYPTION_MASTER_KEY is only allowed outside production.

const FORMAT_VERSION = 'v1';
const IV_BYTES = 12;
const TAG_BYTES = 16;
const DEK_BYTES = 32;

const parseBoolean = (value, fallback = false) => {
    if (value === undefined || value === null || value === '') return fallback;
    const normalized = String(value).trim().toLowerCase();
    return ['1', 'true', 'yes', 'on'].includes(normalized);
};

const isProduction = () => process.env.NODE_ENV === 'production';

let kmsDataKey = null; // { keyVersion, key (Buffer) }
let previousKeys = new Map(); // keyVersion -> Buffer
let primingPromise = null;

const isFieldEncryptionEnabled = () => parseBoolean(process.env.FIELD_ENCRYPTION_ENABLED, false);

const resolveKmsKeyId = () => String(process.env.FIELD_ENCRYPTION_KMS_KEY_ID || '').trim();

const resolveLocalMasterKey = () => String(process.env.FIELD_ENCRYPTION_MASTER_KEY || '').trim();

const buildPreviousKeys = () => {
    const map = new Map();
    String(process.env.FIELD_ENCRYPTION_PREVIOUS_KEYS || '')
        .split(',')
        .map((entry) => entry.trim())
        .filter(Boolean)
        .forEach((entry) => {
            const separator = entry.indexOf(':');
            if (separator <= 0) return;
            const [version, material] = [entry.slice(0, separator).trim(), entry.slice(separator + 1).trim()];
            if (version && material) map.set(version, normalizeKeyMaterial(material));
        });
    return map;
};

// Fixed-salt scrypt is retained ONLY for records already written with the local
// master key. It is not a password KDF (the input is a high-entropy master key,
// not a human passphrase), but a constant salt still means every deployment that
// picked the same master key derives the same DEK, so one deployment's dump is
// readable by another. New local keys derive through HKDF with a frozen context
// instead; the scrypt path stays alive purely to read existing v1 ciphertext.
const LOCAL_KEY_HKDF_CONTEXT = 'field-encryption.local-dek';

const normalizeKeyMaterial = (material) => {
    const raw = Buffer.from(String(material || ''), 'utf8');
    // Accept raw 32 bytes, base64/hex encoded 32 bytes, or derive via HKDF.
    if (raw.length === DEK_BYTES) return raw;
    try {
        const decoded = Buffer.from(String(material || ''), 'base64');
        if (decoded.length === DEK_BYTES) return decoded;
    } catch {
        // fall through to KDF
    }
    try {
        const decoded = Buffer.from(String(material || ''), 'hex');
        if (decoded.length === DEK_BYTES) return decoded;
    } catch {
        // fall through to KDF
    }
    return deriveAes256GcmKey({
        secret: String(material || ''),
        context: LOCAL_KEY_HKDF_CONTEXT,
    });
};

// Frozen: reproduces the old fixed-salt scrypt derivation so local v1 ciphertext
// still decrypts. Never used for new writes.
const normalizeLegacyKeyMaterial = (material) => crypto.scryptSync(
    String(material || ''),
    'aura-field-encryption-kdf',
    DEK_BYTES
);

const assertEnablementContract = () => {
    if (!isFieldEncryptionEnabled()) return;
    if (resolveKmsKeyId()) return;
    if (resolveLocalMasterKey()) {
        if (isProduction()) {
            throw new Error('FIELD_ENCRYPTION_MASTER_KEY is not allowed in production; configure FIELD_ENCRYPTION_KMS_KEY_ID');
        }
        return;
    }
    throw new Error('FIELD_ENCRYPTION_ENABLED requires FIELD_ENCRYPTION_KMS_KEY_ID (or FIELD_ENCRYPTION_MASTER_KEY outside production)');
};

// The wrapped DEK is persisted (KMS-encrypted, never plaintext) so every boot
// recovers the SAME data key. Without this, a fresh GenerateDataKey per boot
// would make all previously-encrypted records unreadable after restarts.
const wrappedDekParameterName = () => `${String(process.env.AWS_PARAMETER_STORE_PATH_PREFIX || '/aura/prod').replace(/\/+$/, '')}/FIELD_ENCRYPTION_WRAPPED_DEK`;

const readWrappedDekRecord = async () => {
    try {
        const { SSMClient, GetParameterCommand } = require('@aws-sdk/client-ssm');
        const client = new SSMClient({});
        const response = await client.send(new GetParameterCommand({
            Name: wrappedDekParameterName(),
            WithDecryption: true,
        }));
        const parsed = JSON.parse(String(response?.Parameter?.Value || '{}'));
        if (!parsed?.wrapped || !parsed?.keyVersion) return null;
        return { keyVersion: String(parsed.keyVersion), wrapped: String(parsed.wrapped) };
    } catch (error) {
        if (error?.name === 'ParameterNotFound' || /ParameterNotFound/.test(String(error?.message))) {
            return null;
        }
        throw error;
    }
};

const persistWrappedDekRecord = async (record) => {
    const { SSMClient, PutParameterCommand } = require('@aws-sdk/client-ssm');
    const client = new SSMClient({});
    const value = JSON.stringify(record);
    try {
        // No --overwrite: a concurrent first boot must not clobber the winner's
        // DEK (records encrypted by it would become unreadable).
        await client.send(new PutParameterCommand({
            Name: wrappedDekParameterName(),
            Type: 'SecureString',
            Value: value,
            Overwrite: false,
        }));
    } catch (error) {
        if (!/AlreadyExists/i.test(String(error?.message)) && error?.name !== 'ParameterAlreadyExists') {
            throw error;
        }
        // Lost the first-boot race: adopt the stored DEK.
        const stored = await readWrappedDekRecord();
        if (!stored) throw new Error('FIELD_ENCRYPTION_WRAPPED_DEK race lost and parameter unreadable');
        return stored;
    }
    return null;
};

const loadKmsDataKey = async () => {
    const keyId = resolveKmsKeyId();
    const { KMSClient, GenerateDataKeyCommand, DecryptCommand } = require('@aws-sdk/client-kms');
    const client = new KMSClient({});

    const stored = await readWrappedDekRecord();
    if (stored) {
        const decrypted = await client.send(new DecryptCommand({
            CiphertextBlob: Buffer.from(stored.wrapped, 'base64url'),
        }));
        if (!decrypted?.Plaintext || decrypted.Plaintext.length !== DEK_BYTES) {
            throw new Error('KMS Decrypt of the stored wrapped DEK returned unexpected key material');
        }
        return { key: Buffer.from(decrypted.Plaintext), keyVersion: stored.keyVersion };
    }

    const response = await client.send(new GenerateDataKeyCommand({ KeyId: keyId, KeySpec: 'AES_256' }));
    if (!response?.Plaintext || response.Plaintext.length !== DEK_BYTES || !response?.CiphertextBlob) {
        throw new Error('KMS GenerateDataKey returned unexpected key material');
    }
    const keyVersion = nextKeyVersion();
    const record = { keyVersion, wrapped: Buffer.from(response.CiphertextBlob).toString('base64url') };
    const adopted = await persistWrappedDekRecord(record);
    if (adopted) {
        const decrypted = await client.send(new DecryptCommand({
            CiphertextBlob: Buffer.from(adopted.wrapped, 'base64url'),
        }));
        return { key: Buffer.from(decrypted.Plaintext), keyVersion: adopted.keyVersion };
    }
    return { key: Buffer.from(response.Plaintext), keyVersion };
};

const loadLocalDataKey = () => normalizeKeyMaterial(resolveLocalMasterKey());

const nextKeyVersion = () => `k${Date.now().toString(36)}${crypto.randomBytes(2).toString('hex')}`;

// Prime the in-memory DEK. Idempotent and safe to call at every startup.
const primeFieldEncryption = async () => {
    assertEnablementContract();
    if (!isFieldEncryptionEnabled()) return { enabled: false };
    if (kmsDataKey) return { enabled: true, cached: true, keyVersion: kmsDataKey.keyVersion };
    if (primingPromise) return primingPromise;

    primingPromise = (async () => {
        previousKeys = buildPreviousKeys();
        let key;
        let keyVersion;
        if (resolveKmsKeyId()) {
            // The data key (and its version) is recovered from the persisted
            // wrapped DEK so records survive restarts; env FIELD_ENCRYPTION_KEY_VERSION
            // only applies to local master-key mode.
            ({ key, keyVersion } = await loadKmsDataKey());
        } else {
            key = loadLocalDataKey();
            keyVersion = String(process.env.FIELD_ENCRYPTION_KEY_VERSION || '').trim() || 'local';
            if (keyVersion === 'local' && previousKeys.has('local')) previousKeys.delete('local');

            // Register the frozen fixed-salt derivation under its own version so
            // local ciphertext written before the HKDF switch still decrypts,
            // without letting it be used for new writes.
            const legacyKey = normalizeLegacyKeyMaterial(resolveLocalMasterKey());
            if (!legacyKey.equals(key)) {
                previousKeys.set('local-legacy-scrypt', legacyKey);
            }
        }
        kmsDataKey = { keyVersion, key };
        logger.info('field_encryption.primed', { keyVersion, provider: resolveKmsKeyId() ? 'kms' : 'local' });
        return { enabled: true, keyVersion };
    })();

    try {
        return await primingPromise;
    } finally {
        primingPromise = null;
    }
};

const requireKeyMaterial = () => {
    if (!kmsDataKey) {
        throw new Error('Field encryption key material is not primed; call primeFieldEncryption() before encrypted reads/writes');
    }
    return kmsDataKey;
};

const b64url = (buffer) => Buffer.from(buffer).toString('base64url');

const encrypt = (plaintext) => {
    if (plaintext === undefined || plaintext === null || plaintext === '') return plaintext;
    if (typeof plaintext !== 'string') plaintext = String(plaintext);
    if (!isFieldEncryptionEnabled()) return plaintext;

    const { key, keyVersion } = requireKeyMaterial();
    const iv = crypto.randomBytes(IV_BYTES);
    const cipher = crypto.createCipheriv('aes-256-gcm', key, iv, { authTagLength: TAG_BYTES });
    let encrypted = cipher.update(plaintext, 'utf8');
    encrypted = Buffer.concat([encrypted, cipher.final()]);
    return [
        FORMAT_VERSION,
        b64url(keyVersion),
        b64url(iv),
        b64url(cipher.getAuthTag()),
        b64url(encrypted),
    ].join('.');
};

const decryptWithKey = (ciphertext, key) => {
    const [, , ivRaw, tagRaw, ctRaw] = ciphertext.split('.');
    const decipher = crypto.createDecipheriv('aes-256-gcm', key, Buffer.from(ivRaw, 'base64url'), {
        authTagLength: TAG_BYTES,
    });
    decipher.setAuthTag(Buffer.from(tagRaw, 'base64url'));
    return Buffer.concat([decipher.update(Buffer.from(ctRaw, 'base64url')), decipher.final()]).toString('utf8');
};

const decrypt = (ciphertext) => {
    if (ciphertext === undefined || ciphertext === null || ciphertext === '') return ciphertext;
    if (typeof ciphertext !== 'string') return ciphertext;
    if (!ciphertext.startsWith(`${FORMAT_VERSION}.`)) return ciphertext; // legacy plaintext (dual-read)

    const [version, keyVersionRaw, ivRaw, tagRaw, ctRaw] = ciphertext.split('.');
    if (version !== FORMAT_VERSION || !keyVersionRaw || !ivRaw || !tagRaw || !ctRaw) return null;

    const keyVersion = Buffer.from(keyVersionRaw, 'base64url').toString('utf8');

    // Ordered candidates: exact version match first, then any previous key, then
    // the current key as a last resort. GCM authentication decides which is
    // correct, so trying several cannot yield a wrong plaintext.
    const candidates = [];
    if (kmsDataKey && kmsDataKey.keyVersion === keyVersion) candidates.push(kmsDataKey.key);
    if (previousKeys.has(keyVersion)) candidates.push(previousKeys.get(keyVersion));
    if (kmsDataKey) candidates.push(kmsDataKey.key);
    for (const previousKey of previousKeys.values()) candidates.push(previousKey);

    const seen = new Set();
    for (const candidate of candidates) {
        if (!candidate || seen.has(candidate)) continue;
        seen.add(candidate);
        try {
            return decryptWithKey(ciphertext, candidate);
        } catch {
            // Wrong key: the auth tag rejected it. Try the next candidate.
        }
    }

    return null;
};

const isEncrypted = (value) => typeof value === 'string' && value.startsWith(`${FORMAT_VERSION}.`);

const isPrimed = () => Boolean(kmsDataKey);

const assertFieldEncryptionConfig = () => assertEnablementContract();

/**
 * Snapshot of the at-rest encryption posture, for logs and health output.
 *
 * `mode` is the honest answer to "is PII encrypted in this process":
 *  - 'kms'         encrypted, keys from AWS KMS
 *  - 'local'       encrypted, local master key (never valid in production)
 *  - 'disabled'    pass-through no-op — plaintext at rest
 */
const getFieldEncryptionStatus = () => {
    const enabled = isFieldEncryptionEnabled();
    const provider = resolveKmsKeyId() ? 'kms' : (enabled && resolveLocalMasterKey() ? 'local' : null);
    const explicitPlaintextOverride = parseBoolean(
        process.env.ALLOW_PLAINTEXT_AT_REST_IN_PRODUCTION,
        false
    );

    let mode = 'disabled';
    if (enabled) mode = resolveKmsKeyId() ? 'kms' : 'local';
    else if (isProduction()) mode = explicitPlaintextOverride ? 'disabled_acknowledged' : 'disabled';

    return {
        enabled,
        mode,
        provider,
        primed: isPrimed(),
        plaintextAtRest: !enabled,
        // True when production is knowingly running without encryption at rest.
        acknowledgedPlaintextAtRest: isProduction() && !enabled && explicitPlaintextOverride,
    };
};

/**
 * Production must not silently store PII in plaintext.
 *
 * `assertEnablementContract` above validates configuration *given* the flag, but
 * deliberately returns early when the flag is off — so a production deploy with
 * FIELD_ENCRYPTION_ENABLED unset boots happily with every address and phone
 * number readable in a database dump. That silent default is the gap this closes.
 *
 * Fails closed. The single escape hatch is ALLOW_PLAINTEXT_AT_REST_IN_PRODUCTION,
 * which exists so an urgent hotfix is never blocked by a config change; it is
 * logged at ERROR level on every boot so the decision is greppable and auditable
 * rather than invisible.
 */
const assertFieldEncryptionProductionReadiness = () => {
    if (!isProduction()) return getFieldEncryptionStatus();

    const status = getFieldEncryptionStatus();
    if (status.enabled) return status;

    if (status.acknowledgedPlaintextAtRest) {
        logger.error('field_encryption.plaintext_at_rest_acknowledged', {
            reason: 'ALLOW_PLAINTEXT_AT_REST_IN_PRODUCTION is set; PII fields are stored in plaintext',
            remediation: 'Set FIELD_ENCRYPTION_ENABLED=true with FIELD_ENCRYPTION_KMS_KEY_ID, then run scripts/backfill-field-encryption.js',
        });
        return status;
    }

    throw new Error(
        'Production refuses to start with encryption at rest disabled. '
        + 'Set FIELD_ENCRYPTION_ENABLED=true and configure FIELD_ENCRYPTION_KMS_KEY_ID '
        + '(then run `node scripts/backfill-field-encryption.js --dry-run`), '
        + 'or explicitly acknowledge plaintext at rest with ALLOW_PLAINTEXT_AT_REST_IN_PRODUCTION=true.'
    );
};

module.exports = {
    primeFieldEncryption,
    encrypt,
    decrypt,
    isEncrypted,
    isFieldEncryptionEnabled,
    isPrimed,
    assertFieldEncryptionConfig,
    assertFieldEncryptionProductionReadiness,
    getFieldEncryptionStatus,
};
