apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aura-staging
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
