apiVersion: v1
kind: ServiceAccount
metadata:
  name: aura-api
  namespace: aura-staging
  labels:
    app.kubernetes.io/name: aura-api
    app.kubernetes.io/part-of: aura-marketplace
automountServiceAccountToken: false
