import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { GENERATED_MARKET_MESSAGES as GENERATED_BASE_MARKET_MESSAGES } from '../src/config/generatedMarketMessages.js';
import { PRIORITY_MARKET_MESSAGES } from '../src/config/priorityMarketMessages.js';
import { GENERATED_MARKET_MESSAGES as GENERATED_LOCALE_MESSAGES } from '../src/config/generatedLocaleMessages.js';
import { GENERATED_DYNAMIC_MARKET_MESSAGES } from '../src/config/generatedDynamicLocaleMessages.js';
import { REMAINING_UI_LOCALE_MESSAGES } from '../src/config/remainingUiLocaleMessages.js';
import { LOCALE_POLISH_MESSAGES } from '../src/config/localePolishMessages.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const CONFIG_ROOT = path.resolve(__dirname, '..', 'src', 'config');
const PACK_ROOT = path.join(CONFIG_ROOT, 'marketMessagePacks');
const SUPPORTED_LANGUAGE_CODES = ['en', 'hi', 'es', 'fr', 'de', 'ar', 'ja', 'pt', 'zh'];

const sortObjectEntries = (value = {}) => Object.fromEntries(
    Object.entries(value || {}).sort(([left], [right]) => left.localeCompare(right))
);

const buildLanguagePack = (languageCode) => {
    if (languageCode === 'en') {
        return sortObjectEntries(GENERATED_BASE_MARKET_MESSAGES.en || {});
    }

    return sortObjectEntries({
        ...(GENERATED_BASE_MARKET_MESSAGES[languageCode] || {}),
        ...(PRIORITY_MARKET_MESSAGES[languageCode] || {}),
        ...(GENERATED_LOCALE_MESSAGES[languageCode] || {}),
        ...(GENERATED_DYNAMIC_MARKET_MESSAGES[languageCode] || {}),
        ...(REMAINING_UI_LOCALE_MESSAGES[languageCode] || {}),
        ...(LOCALE_POLISH_MESSAGES[languageCode] || {}),
    });
};

const writeLanguagePack = (languageCode, messages) => {
    const targetPath = path.join(PACK_ROOT, `${languageCode}.js`);
    const fileContents = `// Generated by scripts/generate_market_message_packs.mjs. Do not edit by hand.\nexport const MARKET_MESSAGE_PACK = ${JSON.stringify(messages, null, 2)};\nexport default MARKET_MESSAGE_PACK;\n`;
    fs.writeFileSync(targetPath, fileContents, 'utf8');
};

const main = () => {
    fs.mkdirSync(PACK_ROOT, { recursive: true });

    SUPPORTED_LANGUAGE_CODES.forEach((languageCode) => {
        const messages = buildLanguagePack(languageCode);
        writeLanguagePack(languageCode, messages);
        console.log(`${languageCode}: ${Object.keys(messages).length} messages`);
    });

    console.log(`Wrote locale packs to ${PACK_ROOT}`);
};

main();
